// =====================================================================
// MATCH HIGHLIGHT TYPES — the structured "what happened" feed the
// new Pixi-based MatchViewer consumes.
//
// Lives separately from the legacy `MatchEvent` (text-only) in
// types/game.ts so existing match logic, ratings, and the season
// rollover stay completely unchanged. The new feed is generated by
// `highlightGenerator.ts` AFTER `simulateMatch` produces its result,
// so QuickSim ≡ Watch Highlights — the viewer only visualises, it
// never decides the result.
// =====================================================================

// =====================================================================
// PITCH ZONES
//
// The pitch is sliced into a 3-row × 3-column grid (defensive third /
// midfield third / attacking third × left / centre / right lane), plus
// three penalty-box sub-zones (left, centre, right) and a single GOAL
// zone behind the line. Total: 13 zones.
//
// Zones are stored from the ATTACKING TEAM'S point of view — i.e.
// DEF_* is the attacking team's own defensive third, ATT_* is in their
// opponents' half, GOAL is the opponents' goal. The viewer takes care
// of mirroring when the away team attacks right→left.
// =====================================================================
export type PitchZone =
  | "DEF_L"
  | "DEF_C"
  | "DEF_R"
  | "MID_L"
  | "MID_C"
  | "MID_R"
  | "ATT_L"
  | "ATT_C"
  | "ATT_R"
  | "BOX_L"
  | "BOX_C"
  | "BOX_R"
  | "GOAL";

/** Lane buckets used when the engine only knows "this play happened
 * on the left wing" — keeps zone selection logic tidy. */
export type PitchLane = "L" | "C" | "R";

/** Vertical thirds — defensive (own end), middle, attacking. */
export type PitchThird = "DEF" | "MID" | "ATT" | "BOX" | "GOAL";

// =====================================================================
// HIGHLIGHT EVENT TYPES
// =====================================================================

/** The play that produced the highlight. Distinct from the OUTCOME of
 * the play (a `cross` can end in `goal`, `save`, `miss`, etc.). */
export type HighlightEventType =
  | "kickoff"
  | "build_up_shot"
  | "counter_attack"
  | "through_ball"
  | "cross"
  | "corner"
  | "free_kick"
  | "penalty"
  | "long_shot"
  | "defensive_mistake"
  | "keeper_save"
  | "goal"
  | "miss"
  | "yellow_card"
  | "red_card"
  | "injury"
  | "substitution"
  | "half_time"
  | "full_time"
  | "late_drama";

/** How the play ended. Drives the viewer's outcome flash + scoreboard. */
export type HighlightOutcome =
  | "goal"
  | "save"
  | "miss"
  | "blocked"
  | "woodwork"
  | "foul"
  | "card"
  | "injury"
  | "kickoff"
  | "half_time"
  | "full_time"
  | "ongoing";

// =====================================================================
// ANIMATION PATH — the sequence of micro-actions the viewer should
// play. Each step is one ball or player movement; the viewer chains
// them back-to-back to make the highlight feel like one continuous
// passage of play.
// =====================================================================

/** Atomic animation primitive. The viewer maps each to one tween. */
export type AnimationAction =
  | "carry"
  | "pass"
  | "through_ball"
  | "cross"
  | "shot"
  | "header"
  | "save"
  | "miss"
  | "goal"
  | "tackle"
  | "foul"
  | "card"
  | "injury"
  | "setpiece"
  | "kickoff_idle";

/** One step in the animation path — the viewer animates the ball
 * (and optionally a player) from `from` → `to` over `durationMs`. */
export interface AnimationStep {
  action: AnimationAction;
  from: PitchZone;
  to: PitchZone;
  /** The player MOVING the ball during this step (carrier on `carry`,
   * passer on `pass`, shooter on `shot`, etc.). Optional for actions
   * the viewer paints from system context (`goal` flash, `kickoff_idle`). */
  playerId?: string;
  /** Intended receiver for `pass` / `through_ball` / `cross`. The
   * viewer can pre-position the receiver near the landing zone so it
   * looks like they ran on to the ball. */
  targetPlayerId?: string;
  /** How long this step takes. The viewer should respect this — total
   * highlight runtime = sum of all step durations. */
  durationMs: number;
}

// =====================================================================
// HIGHLIGHT EVENT
//
// One self-contained "thing that happened" the viewer animates as a
// 6–12 second scene. The shape matches the spec; everything optional
// is something the generator only fills when the underlying play has
// it (e.g. `goalkeeperId` only on shots / saves / goals).
// =====================================================================
export interface HighlightEvent {
  id: string;
  /** Match minute (1–95+). */
  minute: number;
  /** What kind of play this is. */
  type: HighlightEventType;
  /** Side currently in possession at the moment of the event. */
  attackingTeamId: string;
  defendingTeamId: string;

  // ── Players involved ───────────────────────────────────────────
  /** Player who played the final ball into the box / shooter. */
  passerId?: string;
  /** Same as passerId when there's an assist, but kept distinct so the
   * commentary engine can phrase "after a clever pass from X" or
   * "tucked away the rebound" depending on the relationship. */
  assisterId?: string;
  shooterId?: string;
  /** Defender on the play (closest marker, fouler, blocker). */
  defenderId?: string;
  /** Goalkeeper involved — only set on shots / saves / goals. */
  goalkeeperId?: string;

  // ── Outcome + geometry ────────────────────────────────────────
  outcome: HighlightOutcome;
  startZone: PitchZone;
  endZone: PitchZone;
  /** Where the shot was taken from. Only set when the play included a
   * shot (i.e. not for cards / injuries / substitutions). */
  shotZone?: PitchZone;
  /** Expected-goal value of the shot. 0 when there was no shot. */
  xg: number;

  // ── Narrative + animation ─────────────────────────────────────
  /** Short minute-prefixed commentary line. Read aloud by the viewer's
   * commentary bar. */
  description: string;
  /** Bottom-bar "wow" line for goals / red cards / late drama. Optional
   * — most events just use `description`. */
  flavour?: string;
  animationPath: AnimationStep[];
}

// =====================================================================
// MATCH STORY — kept narrative-driven; the same set the legacy engine
// uses, exported here in lowercase for the new highlight-aware code so
// callers don't have to import from game.ts.
// =====================================================================
export type MatchStory =
  | "normal"
  | "favourite_complacent"
  | "underdog_inspired"
  | "keeper_masterclass"
  | "early_red_card"
  | "bad_weather"
  | "cup_shock"
  | "striker_on_fire"
  | "defensive_battle"
  | "derby_chaos"
  | "injury_crisis"
  | "tactical_masterclass"
  | "late_drama";

// =====================================================================
// FORMATION SLOT — formation-shape engine uses these for both teams.
// `x` and `y` are in 0..100 pitch coordinates from the team's OWN
// perspective (x=0 is their goal line, x=100 is the opponents' goal
// line; y=0 is the left touchline, y=100 is the right touchline). The
// viewer mirrors x for the away team.
// =====================================================================
export interface FormationSlot {
  /** Stable id within the formation (e.g. "LB", "CM1", "ST2") so the
   * generator can target specific roles when it picks involved
   * players. */
  id: string;
  /** Coarse role used to slot a real player into this position. */
  role: "GK" | "DEF" | "MID" | "FWD";
  /** Specific role nuance — drives shape-shift behaviour (fullbacks
   * overlap, wingers cut inside, etc.). */
  detail:
    | "GK"
    | "CB"
    | "LB"
    | "RB"
    | "DM"
    | "CM"
    | "AM"
    | "LM"
    | "RM"
    | "LW"
    | "RW"
    | "ST"
    | "CF";
  /** 0..100 own-end → opponents'-end. */
  x: number;
  /** 0..100 left touchline → right touchline. */
  y: number;
}

export type FormationKey = "4-4-2" | "4-3-3" | "3-5-2" | "4-2-3-1" | "5-3-2" | "4-5-1";

/** The "what mode is the team in" parameter used by `getShiftedTeamShape`. */
export type TeamPhase = "neutral" | "attack" | "defend";
